import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';
import { hashingRounds } from '../src/users/users.service';

const prisma = new PrismaClient();

async function main() {
  const hashedPassword = await bcrypt.hash('123123', hashingRounds);

  const user1 = await prisma.user.upsert({
    where: { email: 'user1@example.com' },
    update: {},
    create: {
      email: 'user1@example.com',
      password: hashedPassword,
    },
  });
  const user2 = await prisma.user.upsert({
    where: { email: 'user2@example.com' },
    update: {},
    create: {
      email: 'user2@example.com',
      password: hashedPassword,
    },
  });
  console.log({ user1, user2 });

  const video1 = await prisma.video.create({
    data: {
      title: 'Put Your Head On My Shoulder',
      youtubeUrl: 'https://youtu.be/kvazBqAlx58?si=SRlyhUAUbJRsxZ4p',
      youtubeId: 'kvazBqAlx58',
      description: `Provided to YouTube by The Orchard Enterprises

      Put Your Head On My Shoulder · Paul Anka
      
      Paul Anka's Early Years
      
      ℗ 2011 BringIns Music
      
      Released on: 2011-04-06
      
      Auto-generated by YouTube.`,
      userId: user1.id,
    },
  });

  const video2 = await prisma.video.create({
    data: {
      title: 'Coffee Time with Lofi ☕️ : A Relaxing Break 🌿',
      youtubeUrl: 'https://youtu.be/7zxbFpIkHzk?si=CmQTm2iopEtxo1j5',
      youtubeId: '7zxbFpIkHzk',
      description: `Escape the day's hustle and unwind with a cup of aromatic coffee accompanied by Lofi music. This gentle melody offers a serene respite for both mind and body. Why not take a step back from the daily grind and relax with the scent of coffee?`,
      userId: user1.id,
    },
  });

  const video3 = await prisma.video.create({
    data: {
      title: 'Frank Sinatra   I Love You Baby',
      youtubeUrl: 'https://youtu.be/AiIBKcd4m5Q?si=hGdYL1GN92pHsZUa',
      youtubeId: 'AiIBKcd4m5Q',
      description: `Lyrics :
      You're just too good to be true can't take my eyes off of you
      You'd be like heaven to touch I wanna hold you so much
      And long last love has arrived and I thank God I'm alive
      You're just too good to be true can't take my eyes off of you
      `,
      userId: user2.id,
    },
  });

  const video4 = await prisma.video.create({
    data: {
      title: 'George Michael - Careless Whisper (Official Video)',
      youtubeUrl: 'https://youtu.be/izGwDsrQ1eQ?si=UCqAsiaoDgBI-usW',
      youtubeId: 'izGwDsrQ1eQ',
      description: `I feel so unsure
      As I take your hand
      And lead you to the dance floor
      As the music dies
      Something in your eyes
      Calls to mind a silver screen
      And all its sad goodbyes
      `,
      userId: user2.id,
    },
  });

  console.log({ video1, video2, video3, video4 });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
